name: Publish

# on:
#  release:
#    types: [created]
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # SDK Version to use.
      - name: Build and pack the project
        run: dotnet build --configuration Release
      # - name: Publish TextTabulator package to nuget.org
      #   run: dotnet nuget push src/TextTabulator/bin/Release/*.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
      - name: Publish TextTabulator.Adapters package to nuget.org
        run: dotnet nuget push src/TextTabulator.Adapters/bin/Release/*.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
      # - name: Publish TextTabulator.Adapters.CsvHelper package to nuget.org
      #   run: dotnet nuget push src/TextTabulator.Adapters.CsvHelper/bin/Release/*.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
      # - name: Publish TextTabulator.Adapters.Reflection package to nuget.org
      #   run: dotnet nuget push src/TextTabulator.Adapters.Reflection/bin/Release/*.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
      # - name: Publish TextTabulator.Adapters.Json package to nuget.org
      #   run: dotnet nuget push src/TextTabulator.Adapters.Json/bin/Release/*.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
      # - name: Publish TextTabulator.Adapters.Xml package to nuget.org
      #   run: dotnet nuget push src/TextTabulator.Adapters.Xml/bin/Release/*.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
